version: "3"

services:

  springdb:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: account
      MYSQL_USER: user
      MYSQL_PASSWORD: secretpass
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

  springapp:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - springdb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://springdb:3306/account?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

volumes:
  db_data:
